In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

In [11]:
DataFrame1_SE = pd.DataFrame({"StudentId":[9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                           "ScoreSE":[22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
DataFrame2_SE = pd.DataFrame({"StudentId":[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
                              "ScoreSE":[98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

In [10]:
DataFrame1_ML = pd.DataFrame({"StudentId":[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                              "ScoreML":[39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
DataFrame2_ML = pd.DataFrame({"StudentId":[2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                              "ScoreML":[93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [9]:
dfSE=pd.concat([DataFrame1_SE,DataFrame2_SE],ignore_index=True)
dfSE

    StudentId  ScoreSE
0           9       22
1          11       66
2          13       31
3          15       51
4          17       71
5          19       91
6          21       56
7          23       32
8          25       52
9          27       73
10         29       92
11          2       98
12          4       93
13          6       44
14          8       77
15         10       69
16         12       56
17         14       31
18         16       53
19         18       78
20         20       93
21         22       56
22         24       77
23         26       33
24         28       56
25         30       27

In [12]:
dfML=pd.concat([DataFrame1_ML,DataFrame2_ML],ignore_index=True)
dfML

    StudentId  ScoreML
0           1       39
1           3       49
2           5       55
3           7       77
4           9       52
5          11       86
6          13       41
7          15       77
8          17       73
9          19       51
10         21       86
11         23       82
12         25       92
13         27       23
14         29       49
15          2       93
16          4       44
17          6       78
18          8       97
19         10       87
20         12       89
21         14       39
22         16       43
23         18       88
24         20       78

In [13]:
df = pd.concat([dfML, dfSE], axis=1)
df

    StudentId  ScoreML  StudentId  ScoreSE
0         1.0     39.0          9       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          6       44
14       29.0     49.0          8       77
15        2.0     93.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         14       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

In [16]:
dfSE = pd.concat([DataFrame1_SE,DataFrame2_SE],ignore_index=True)
dfML = pd.concat([DataFrame1_ML,DataFrame2_ML],ignore_index=True)
df = dfSE.merge(dfML,how="inner")
df

    StudentId  ScoreSE  ScoreML
0           9       22       52
1          11       66       86
2          13       31       41
3          15       51       77
4          17       71       73
5          19       91       51
6          21       56       86
7          23       32       82
8          25       52       92
9          27       73       23
10         29       92       49
11          2       98       93
12          4       93       44
13          6       44       78
14          8       77       97
15         10       69       87
16         12       56       89
17         14       31       39
18         16       53       43
19         18       78       88
20         20       93       78

In [17]:
dfSE = pd.concat([DataFrame1_SE,DataFrame2_SE], ignore_index=True)
dfML = pd.concat([DataFrame1_ML,DataFrame2_ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

    StudentId  ScoreSE  ScoreML
0           9       22     52.0
1          11       66     86.0
2          13       31     41.0
3          15       51     77.0
4          17       71     73.0
5          19       91     51.0
6          21       56     86.0
7          23       32     82.0
8          25       52     92.0
9          27       73     23.0
10         29       92     49.0
11          2       98     93.0
12          4       93     44.0
13          6       44     78.0
14          8       77     97.0
15         10       69     87.0
16         12       56     89.0
17         14       31     39.0
18         16       53     43.0
19         18       78     88.0
20         20       93     78.0
21         22       56      NaN
22         24       77      NaN
23         26       33      NaN
24         28       56      NaN
25         30       27      NaN

In [18]:
dfSE = pd.concat([DataFrame1_SE,DataFrame2_SE], ignore_index=True)
dfML = pd.concat([DataFrame1_ML,DataFrame2_ML], ignore_index=True)

df = dfSE.merge(dfML, how='right')
df

    StudentId  ScoreSE  ScoreML
0           1      NaN       39
1           3      NaN       49
2           5      NaN       55
3           7      NaN       77
4           9     22.0       52
5          11     66.0       86
6          13     31.0       41
7          15     51.0       77
8          17     71.0       73
9          19     91.0       51
10         21     56.0       86
11         23     32.0       82
12         25     52.0       92
13         27     73.0       23
14         29     92.0       49
15          2     98.0       93
16          4     93.0       44
17          6     44.0       78
18          8     77.0       97
19         10     69.0       87
20         12     56.0       89
21         14     31.0       39
22         16     53.0       43
23         18     78.0       88
24         20     93.0       78