<a href="https://colab.research.google.com/github/HarshKumar1244vitvellore/Exploratory-data-analysis/blob/main/Experiment4-28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

In [3]:
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [4]:
dfx['Store4'] = np.nan

In [5]:
dfx.loc['watermelon'] = np.arange(15, 19)

In [6]:
dfx.loc['watermelon'] = np.arange(15, 19)

In [8]:
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan

In [9]:
dfx

            store1  store2  store3  Store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [10]:
dfx['Store4']['Apple'] = 20

/tmp/ipykernel_2667/2609650744.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['Store4']['Apple'] = 20

In [11]:
dfx

            store1  store2  store3  Store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [12]:
dfx.isnull()

            store1  store2  store3  Store4  store5
apple        False   False   False    True    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [13]:
dfx.notnull()

            store1  store2  store3  Store4  store5
apple         True    True    True   False   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [14]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
Store4    6
store5    7
dtype: int64

In [15]:
dfx.isnull().sum().sum()

np.int64(16)

In [16]:
dfx.count()

store1    6
store2    6
store3    6
Store4    1
store5    0
dtype: int64

In [17]:
dfx.mean()

store1    20.0
store2    21.0
store3    22.0
Store4    18.0
store5     NaN
dtype: float64

In [18]:
dfx.median()

store1    19.5
store2    20.5
store3    21.5
Store4    18.0
store5     NaN
dtype: float64

In [19]:
dfx.mode()

   store1  store2  store3  Store4  store5
0    15.0    16.0    17.0    18.0     NaN

In [22]:
dfx.Store4[dfx.Store4.notnull()]

watermelon    18.0
Name: Store4, dtype: float64

In [23]:
dfx.Store4.dropna()

watermelon    18.0
Name: Store4, dtype: float64