In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl

In [2]:
df_2 = pd.read_csv("/content/Suicide data.csv")
df_2

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [3]:
df_2.max()

country                   Uzbekistan
year                            2016
sex                             male
age                        75+ years
suicides_no                    22338
population                  43805214
suicides/100k pop             224.97
country-year          Uzbekistan2014
HDI for year                   0.944
 gdp_for_year ($)        997,007,926
gdp_per_capita ($)            126352
generation                    Silent
dtype: object

In [4]:
df_2.min()

country                         Albania
year                               1985
sex                              female
age                         15-24 years
suicides_no                           0
population                          278
suicides/100k pop                   0.0
country-year                Albania1987
HDI for year                      0.483
 gdp_for_year ($)     1,002,219,052,968
gdp_per_capita ($)                  251
generation                      Boomers
dtype: object

In [5]:
df_2.min()

country                         Albania
year                               1985
sex                              female
age                         15-24 years
suicides_no                           0
population                          278
suicides/100k pop                   0.0
country-year                Albania1987
HDI for year                      0.483
 gdp_for_year ($)     1,002,219,052,968
gdp_per_capita ($)                  251
generation                      Boomers
dtype: object

In [6]:
df_2.mode()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Austria,2009.0,female,15-24 years,0.0,24000.0,0.0,Albania1987,0.713,"1,002,219,052,968",1299.0,Generation X
1,Iceland,NaN,male,25-34 years,NaN,NaN,NaN,Albania1988,0.772,"1,011,797,457,139",2303.0,NaN
2,Mauritius,NaN,NaN,35-54 years,NaN,NaN,NaN,Albania1989,0.888,"1,016,418,229",4104.0,NaN
3,Netherlands,NaN,NaN,55-74 years,NaN,NaN,NaN,Albania1992,NaN,"1,018,847,043,277",NaN,NaN
4,NaN,NaN,NaN,75+ years,NaN,NaN,NaN,Albania1993,NaN,"1,022,191,296",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2010,NaN,"99,698,453,261",NaN,NaN
2301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2011,NaN,"99,853,528,653",NaN,NaN
2302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2012,NaN,"99,886,577,331",NaN,NaN
2303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2013,NaN,"990,374,050",NaN,NaN
2304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2014,NaN,"997,007,926",NaN,NaN

In [9]:
df_2.head()
df_2.tail()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [10]:
df_2.mean(numeric_only=True)

year                  2.001258e+03
suicides_no           2.425744e+02
population            1.844794e+06
suicides/100k pop     1.281610e+01
HDI for year          7.766011e-01
gdp_per_capita ($)    1.686646e+04
dtype: float64

In [13]:
df_2.mean(numeric_only=True)
df_2.median(numeric_only=True)

year                    2002.000
suicides_no               25.000
population            430150.000
suicides/100k pop          5.990
HDI for year               0.779
gdp_per_capita ($)      9372.000
dtype: float64